---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
