---
- name: "Install Fluentbit prerequisites."
  apt:
    name: "{{ fluentbit_prerequisites }}"
    state: present

- name: "Cleanup legacy apt configuration."
  when: fluentbit_apt_cleanup_legacy | bool
  block:
    - name: "Cleanup legacy key in main keyring if needed."
      apt_key:
        id: "{{ fluentbit_apt_key_legacy_id }}"
        state: absent
    - name: "Cleanup legacy key in custom keyring if needed."
      apt_key:
        keyring: "{{ fluentbit_apt_key_path }}"
        id: "{{ fluentbit_apt_key_legacy_id }}"
        state: absent
    - name: "Cleanup legacy Fluentbit repository definition."
      apt_repository:
        repo: "deb {{ fluentbit_apt_repos_url }} {{ ansible_distribution_release | lower }} main"
        update_cache: True
        filename: fluentbit
        state: absent
# End of block

- name: "Add Fluentbit key."
  apt_key:
    url: "{{ fluentbit_apt_key_url }}"
    keyring: "{{ fluentbit_apt_key_path | default(omit) }}"
    state: present

- name: "Add Fluentbit repository."
  apt_repository:
    repo: |
      deb [signed-by={{ fluentbit_apt_key_path }}] {{ fluentbit_apt_repos_url }}
      {{ ansible_distribution_release | lower }} {{ fluentbit_apt_repos_component }}
    filename: fluentbit
    state: present

- name: "Get installed Fluentbit version."
  command: dpkg-query --showformat='${Version}' --show {{ fluentbit_pkg_name }}
  register: fluentbit_pkg_installed_version
  failed_when: false
  changed_when: false
  check_mode: false

- name: "Unhold Fluentbit version."
  dpkg_selections:
    name: "{{ fluentbit_pkg_name }}"
    selection: install
  when: not fluentbit_pkg_version_hold or (fluentbit_pkg_installed_version.stdout and fluentbit_pkg_installed_version.stdout != fluentbit_pkg_version)

- name: "Install Fluentbit."
  apt:
    name: "{{ fluentbit_pkg_name }}{% if fluentbit_pkg_version is defined and fluentbit_pkg_version != '' %}={{ fluentbit_pkg_version }}{% endif %}"
    update_cache: true
    state: present
  notify: "Restart Fluentbit."

- name: "Hold Fluentbit version."
  dpkg_selections:
    name: "{{ fluentbit_pkg_name }}"
    selection: "hold"
  when: fluentbit_pkg_version_hold

- name: "Create needed directory."
  file:
    path: "{{ fluentbit_dbs_path }}"
    state: directory
    mode: 0755
  when: fluentbit_dbs_path | length > 0

- name: "Enable Fluentbit service."
  service:
    name: "{{ fluentbit_svc_name }}"
    enabled: true

- name: "Create main Fluentbit configuration."
  template:
    src: td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644
  notify: "Restart Fluentbit."

- name: "Create needed directory."
  file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d"
    state: directory
    mode: 0755
  when: fluentbit_svc_limit_open_files is defined

- name: "Override systemd configuration if needed."
  template:
    src: td-agent-bit-override.conf.j2
    dest: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    mode: 0644
  register: _override
  when: fluentbit_svc_limit_open_files is defined

- name: "Delete ovveride systemd configuration if needed."
  file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    state: absent
  when: fluentbit_svc_limit_open_files is not defined
  register: _override
