---
- name: "Install Fluentbit prerequisites."
  ansible.builtin.apt:
    name: "{{ fluentbit_prerequisites }}"
    state: present

- name: "Import tasks needed to cleanup legacy stuff."
  ansible.builtin.import_tasks: cleanup.yml

- name: "Add Fluentbit repository."
  ansible.builtin.deb822_repository:
    name: fluentbit
    types: deb
    uris: "{{ fluentbit_apt_repos_url }}"
    suites: "{{ ansible_distribution_release | lower }}"
    components: "{{ fluentbit_apt_repos_component }}"
    signed_by: "{{ fluentbit_apt_key_url }}"

- name: "Install Fluentbit."
  ansible.builtin.apt:
    name: "{{ fluentbit_pkg_name }}{% if fluentbit_pkg_version is defined and fluentbit_pkg_version != '' %}={{ fluentbit_pkg_version }}{% endif %}"
    update_cache: true
    allow_change_held_packages: true
    state: present
  notify: "Restart Fluentbit."

- name: "Hold Fluentbit version."
  ansible.builtin.dpkg_selections:
    name: "{{ fluentbit_pkg_name }}"
    selection: "hold"
  when: fluentbit_pkg_version_hold

- name: "Create needed directory."
  ansible.builtin.file:
    path: "{{ fluentbit_dbs_path }}"
    state: directory
    mode: "0755"
  when: fluentbit_dbs_path | length > 0

- name: "Enable Fluentbit service."
  ansible.builtin.systemd:
    name: "{{ fluentbit_svc_name }}"
    enabled: true

- name: "Create main Fluentbit configuration."
  ansible.builtin.template:
    src: fluent-bit.conf.j2
    dest: "{{ fluentbit_conf_file_path }}"
    mode: "0644"
  notify: "Restart Fluentbit."

- name: "Create ansible managed parser file if needed."
  ansible.builtin.template:
    src: managed-parsers.conf.j2
    dest: "{{ fluentbit_managed_parsers_file }}"
    mode: "0644"
  notify: "Restart Fluentbit."
  when:
    - fluentbit_managed_parsers_enable is defined
    - fluentbit_managed_parsers_enable | bool

- name: "Create needed directory."
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d"
    state: directory
    mode: "0755"
  when: fluentbit_svc_limit_open_files is defined

- name: "Override systemd configuration if needed."
  ansible.builtin.template:
    src: fluent-bit-override.conf.j2
    dest: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    mode: "0644"
  when: fluentbit_svc_limit_open_files is defined

- name: "Delete override systemd configuration if needed."
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ fluentbit_svc_name }}.service.d/override.conf"
    state: absent
  when: fluentbit_svc_limit_open_files is not defined
