---
- ansible.builtin.include_tasks: debian.yml
  listen: "Restart Fluentbit."
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: windows.yml
  listen: "Restart Fluentbit."
  when: ansible_os_family == 'Windows'
