FROM {{ item.image }}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    python3 python3-apt \
    sudo bash ca-certificates iproute2 cron \
    systemctl

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
