---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: fluentbit_bullseye_${TOX_ENV_NAME}
    image: debian:bullseye
    pre_build_image: false
  - name: fluentbit_bookworm_${TOX_ENV_NAME}
    image: debian:bookworm
    pre_build_image: false
  # Will be added when the needed fixes are done
  # - name: fluentbit_trixie_${TOX_ENV_NAME}
  #   image: debian:trixie
  #   pre_build_image: false

  - name: fluentbit_focal_${TOX_ENV_NAME}
    image: ubuntu:focal
    pre_build_image: false
  - name: fluentbit_jammy_${TOX_ENV_NAME}
    image: ubuntu:jammy
    pre_build_image: false
  # Will be added when the needed fixes are done
  # - name: fluentbit_oracular_${TOX_ENV_NAME}
  #   image: ubuntu:oracular
  #   pre_build_image: false

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  inventory:
    group_vars:
      all:
        fluentbit_pkg_name: "fluent-bit"
        fluentbit_svc_name: "fluent-bit"
        fluentbit_file_input:
          name: tail
          alias: file_input
          path: /var/log/log_input
          read_from_head: true
          refresh_interval: 1
        fluentbit_test_filter:
          name: modify
          alias: modify_filter
          match: '*'
          0__add: test JUST_A_TEST
          1__add: test2 JUST_A_TEST2
        fluentbit_file_output:
          name: file
          match: '*'
          path: /var/log
          file: check_output.txt

scenario:
  name: default
  test_sequence:
    - create
    - converge
    - verify
    - destroy
