---
- name: Verify
  hosts: all
  tasks:
    - name: "Create fake log file"
      ansible.builtin.file:
        path: "{{ fluentbit_file_input.path }}"
        mode: "0644"
        state: touch
    - name: "Generate some fake log"
      ansible.builtin.lineinfile:
        path: "{{ fluentbit_file_input.path }}"
        line: "This is a test message."
    - name: "Check if fluentbit is installed"
      ansible.builtin.package:
        name: "{{ fluentbit_pkg_name }}"
        state: present
      register: pkg_install
      check_mode: true
      failed_when: pkg_install is changed or pkg_install is failed
    - name: "Check if fluentbit service is running"
      ansible.builtin.systemd:
        name: "{{ fluentbit_svc_name }}"
        state: started
        enabled: true
      register: svc_conf
      check_mode: true
      failed_when: svc_conf is changed or svc_conf is failed
    - name: "Check if the log is process"
      ansible.builtin.wait_for:
        path: "{{ fluentbit_file_output.path }}/{{ fluentbit_file_output.file }}"
        search_regex: "JUST_A_TEST"
        timeout: 30
