name: main

on:
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--offline"
          setup_python: "false"

  test:
    name: Tox - Molecule test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run the tests
        run: tox
